options(encoding = "UTF-8")
find_root <- function(path) { current <- normalizePath(path, winslash = "/", mustWork = TRUE); repeat { if (file.exists(file.path(current, ".codex", "study-mmrm-analysis", "R", "analysis_plan.R"))) return(current); parent <- dirname(current); if (parent == current) stop("project root not found"); current <- parent } }
project_dir <- find_root(getwd()); helper_dir <- file.path(project_dir, ".codex", "study-mmrm-analysis", "R")
for (helper in c("canonical_hash.R", "standard_analysis_definition.R", "analysis_plan.R")) source(file.path(helper_dir, helper), encoding = "UTF-8")
source(file.path(project_dir, ".codex", "study-mmrm-analysis", "scripts", "check_analysis_plan.R"), local = globalenv(), encoding = "UTF-8")
explicit <- synthetic_analysis_plan()
validate_analysis_plan(explicit, synthetic_trace_ids())
stopifnot(identical(explicit$analyses[[1]]$mappings$response, "DELTA_SCORE"), identical(explicit$analyses[[1]]$covariance$fallback, list("CS", "AR1")))
ambiguous <- analysis_plan_template("SYNTHETIC", list(list(tfl_id = "T14-01", title = "Synthetic")))
stopifnot(inherits(try(validate_analysis_plan(ambiguous), silent = TRUE), "try-error"))
missing_trace <- explicit; missing_trace$analyses[[1]]$trace$covariance <- list()
stopifnot(inherits(try(validate_analysis_plan(missing_trace, synthetic_trace_ids()), silent = TRUE), "try-error"))
default_insertion <- explicit; default_insertion$analyses[[1]]$covariance$primary <- "UN"; default_insertion$analyses[[1]]$trace$covariance <- list("PROFILE-DEFAULT")
stopifnot(inherits(try(validate_analysis_plan(default_insertion, synthetic_trace_ids()), silent = TRUE), "try-error"))
cat("Analysis plan compilation focused check passed.\n")
