options(encoding = "UTF-8")
find_root <- function(path) { current <- normalizePath(path, winslash = "/", mustWork = TRUE); repeat { if (file.exists(file.path(current, ".codex", "study-mmrm-analysis", "R", "review_finalization.R"))) return(current); parent <- dirname(current); if (parent == current) stop("project root not found"); current <- parent } }
project_dir <- find_root(getwd()); helper_dir <- file.path(project_dir, ".codex", "study-mmrm-analysis", "R")
for (helper in c("canonical_hash.R", "standard_contract.R", "standard_analysis_definition.R", "analysis_plan.R", "analysis_contract_generation.R", "standard_sas.R", "io.R", "specification.R", "review_finalization.R", "analysis_approval.R")) source(file.path(helper_dir, helper), encoding = "UTF-8")
if (!requireNamespace("digest", quietly = TRUE) || !requireNamespace("yaml", quietly = TRUE)) stop("digest and yaml are required")
rscript_path <- file.path(R.home("bin"), if (.Platform$OS.type == "windows") "Rscript.exe" else "Rscript")
finalization_cli <- file.path(project_dir, ".codex", "study-mmrm-analysis", "scripts", "finalize_statistical_review.R")
self_check_output <- suppressWarnings(system2(rscript_path, c("--vanilla", shQuote(finalization_cli), "--self-check=true"), stdout = TRUE, stderr = TRUE))
self_check_status <- attr(self_check_output, "status"); if (is.null(self_check_status)) self_check_status <- 0L
stopifnot(identical(as.integer(self_check_status), 0L), any(grepl("Review finalization self-check passed", self_check_output, fixed = TRUE)))
study_dir <- tempfile("zz_analysis_plan_finalization_", tmpdir = project_dir); dir.create(file.path(study_dir, "input"), recursive = TRUE); dir.create(file.path(study_dir, "backup-trace"), recursive = TRUE); dir.create(file.path(study_dir, "statistician-review"), recursive = TRUE); on.exit(unlink(study_dir, recursive = TRUE, force = TRUE), add = TRUE)
source_path <- file.path(study_dir, "input", "scores.csv"); write_utf8_bom_csv(data.frame(PERSON_ID = "P1", DELTA_SCORE = 1, START_SCORE = 0, TIME_INDEX = 1, PARAMCD = "SCORE_A"), source_path)
manifest <- data.frame(source_id = "SRC-DATA-01", input_type = "analysis_dataset", file_name = "scores.csv", relative_path = "input/scores.csv", version = "1", file_size_bytes = file.info(source_path)$size, modified_at = "2026-08-19T00:00:00Z", sha256 = toupper(digest::digest(file = source_path, algo = "sha256")), status = "linked_source", note = "synthetic", stringsAsFactors = FALSE)
write_utf8_bom_csv(manifest, file.path(study_dir, "backup-trace", "input-manifest.csv")); registry <- source_evidence_registry(project_dir, study_dir); evidence_id <- registry$ids[[1L]]; study_id <- basename(study_dir)
review_path <- file.path(study_dir, "statistician-review", "statistical-review.md")
metadata <- list(review_schema_version = "2.0", study_id = study_id, generation_route = "synthetic_check", review_status = "pending", reviewed_by = "", reviewed_at_utc = "", finalization_status = "pending", source_manifest_file = project_relative_path(file.path(study_dir, "backup-trace", "input-manifest.csv"), project_dir), analysis_plan_file = "", analysis_plan_sha256 = "", source_evidence_sha256 = "", review_execution_content_sha256 = "", approval_payload_sha256 = "")
body <- c("# Synthetic statistical review", "", "## 1. \u5ba1\u9605\u7ed3\u8bba\u4e0e\u7b7e\u6838", "Pending.", "", "## 2. Study \u4e0e\u6570\u636e\u8303\u56f4", "Synthetic evidence.", "", "## 3. Analysis \u4e0e TFL \u6e05\u5355", "Typed plan only.", "", "## 4. Analysis Plan\uff08\u53ea\u8bfb\uff09", "<!-- ANALYSIS_PLAN_BEGIN -->", "Pending.", "<!-- ANALYSIS_PLAN_END -->", "", "## 5. \u6a21\u578b\u3001\u534f\u65b9\u5dee\u4e0e\u4f30\u8ba1\u91cf\u786e\u8ba4", "Typed plan only.", "", "## 6. Adapter / \u6d3e\u751f / \u884c\u5206\u914d\u786e\u8ba4", "Typed plan only.", "", "## 7. \u672a\u89e3\u51b3\u95ee\u9898\u4e0e\u51b3\u8bae", "| issue_id | scope | question_or_risk | resolution | status |", "|---|---|---|---|---|", "", "## 8. Approval Payload \u6307\u7eb9", "Pending.")
writeLines(c("---", strsplit(yaml::as.yaml(metadata), "\n", fixed = TRUE)[[1]], "---", "", body), review_path, useBytes = TRUE)
dimensions <- list(instrument = list(variable = "not_applicable", values = character()), version = list(variable = "not_applicable", values = character()), reporter = list(variable = "not_applicable", values = character()), subscale = list(variable = "not_applicable", values = character()))
trace <- setNames(rep(list(list()), length(analysis_plan_trace_keys())), analysis_plan_trace_keys()); for (name in c("dataset", "mappings", "groups", "endpoint_definitions", "model_terms", "reml", "covariance", "df_method", "estimands")) trace[[name]] <- list(evidence_id)
analysis <- list(analysis_id = "MMRM-01", source_tfl_id = "T14-01", title = "Synthetic single-arm", dataset = list(binding_mode = "linked", file = "scores.csv", format = "csv", relative_path = project_relative_path(source_path, project_dir), sha256 = toupper(digest::digest(file = source_path, algo = "sha256"))), adapter = NULL, mappings = list(subject = "PERSON_ID", response = "DELTA_SCORE", baseline = "START_SCORE", visit = "TIME_INDEX"), derivations = list(), filters = list(), groups = list(list(id = "TOTAL", label = "Total", predicates = list(list(variable = "PARAMCD", operator = "eq", value = "SCORE_A")))), endpoint_definitions = list(list(group_id = "TOTAL", endpoint_variable = "PARAMCD", selected_codes = "SCORE_A", selection_mode = "single_code", dimensions = dimensions, row_allocation_rule = "one_row_per_subject_endpoint_visit")), model_terms = list(list(kind = "main_effect", role = "visit"), list(kind = "main_effect", role = "baseline"), list(kind = "interaction", of = list("baseline", "visit"))), reml = TRUE, covariance = list(primary = "UN", fallback = as.list(c("AR1", "CS"))), df_method = "Kenward-Roger", estimands = list(visit_lsmeans = TRUE, treatment_visit_lsmeans = FALSE, pairwise_differences = FALSE), treatment = NULL, trace = trace)
plan <- list(analysis_plan_schema_version = "2.2", study_id = study_id, execution_context = list(profile_version = standard_mmrm_profile_version(), data_availability = "available", data_classification = "dummy", intended_use = "technical_validation", sas_execution_profile = "sas-9.4m5-self-contained/v1"), analyses = list(analysis))
hash_names <- c("analysis_plan_sha256", "source_evidence_sha256", "review_execution_content_sha256", "approval_payload_sha256")
# 新流程：AI Compile 产出 candidate + 置 ready_for_compilation；R finalize 校验 candidate 并把它提升为正式 plan、review 置 approved/published。
compile_and_finalize <- function(candidate_plan, source_review = review_path) {
  analysis_plan_write(candidate_plan, analysis_plan_candidate_path(study_dir))
  lines <- statistical_review_set_metadata(readLines(source_review, encoding = "UTF-8", warn = FALSE), "review_status", "ready_for_compilation")
  writeLines(lines, source_review, useBytes = TRUE)
  finalize_statistical_review(study_dir, source_review, review_path, "Synthetic Reviewer", allow_unresolved = TRUE)
}
# 1) 校验通过：candidate 提升为正式 analysis-plan.yaml + review approved/published；candidate 删除。
first <- compile_and_finalize(plan); if (!isTRUE(first$published)) stop(paste(first$issues$observed, collapse = " | ")); stopifnot(first$approved, first$analysis_count == 1L, file.exists(analysis_plan_path(study_dir)), !file.exists(analysis_plan_candidate_path(study_dir)))
final_review <- read_statistical_review(review_path); finalized <- final_review$metadata; stopifnot(identical(as.character(finalized$review_status), "approved"), identical(as.character(finalized$finalization_status), "published"), nzchar(as.character(finalized$reviewed_by)), statistical_review_iso_utc(finalized$reviewed_at_utc), all(vapply(finalized[hash_names], function(x) grepl("^[A-F0-9]{64}$", x), logical(1))), grepl("DELTA_SCORE", paste(statistical_review_section_lines(final_review, statistical_review_required_headings()[[4L]]), collapse = "\n"), fixed = TRUE))
formal_plan_sha <- file_sha256(analysis_plan_path(study_dir))
# 2) 确定性：再次 compile+finalize 得到相同 hashes 与相同正式 plan 字节。
hashes <- unlist(finalized[hash_names]); second <- compile_and_finalize(plan); stopifnot(second$approved); rerun <- read_statistical_review(review_path); stopifnot(identical(hashes, unlist(rerun$metadata[hash_names])), identical(formal_plan_sha, file_sha256(analysis_plan_path(study_dir))))
# 3) review study_id 与目录不符：不发布、不写 review、正式 plan 不变。
before_review <- file_sha256(review_path); before_plan <- file_sha256(analysis_plan_path(study_dir))
bad_review_path <- tempfile("wrong-study-review-", fileext = ".md"); on.exit(unlink(bad_review_path, force = TRUE), add = TRUE)
bad_lines <- statistical_review_set_metadata(rerun$lines, "study_id", "wrong-study"); bad_lines <- statistical_review_set_metadata(bad_lines, "review_status", "ready_for_compilation"); writeLines(bad_lines, bad_review_path, useBytes = TRUE)
analysis_plan_write(plan, analysis_plan_candidate_path(study_dir))
bad_review_result <- finalize_statistical_review(study_dir, bad_review_path, review_path, "Synthetic Reviewer", allow_unresolved = TRUE); stopifnot(!bad_review_result$published, any(bad_review_result$issues$issue_id == "PLAN-SCHEMA-STUDY-ID"), identical(before_review, file_sha256(review_path)), identical(before_plan, file_sha256(analysis_plan_path(study_dir))))
# 4) candidate study_id 与目录不符：blocked review(pending)、hash 清空、Section7 有 blocker、正式 plan 不变。
bad_plan <- plan; bad_plan$study_id <- "wrong-study"; bad_plan_result <- compile_and_finalize(bad_plan); stopifnot(bad_plan_result$published, !bad_plan_result$approved, any(bad_plan_result$issues$issue_id == "PLAN-SCHEMA-STUDY-ID"), identical(before_plan, file_sha256(analysis_plan_path(study_dir))))
blocked_review <- read_statistical_review(review_path); stopifnot(identical(as.character(blocked_review$metadata$review_status), "pending"), identical(as.character(blocked_review$metadata$finalization_status), "blocked_pending_resolution"), all(vapply(blocked_review$metadata[hash_names], function(x) !nzchar(as.character(x)), logical(1))), any(grepl("PLAN-SCHEMA-STUDY-ID", statistical_review_section_lines(blocked_review, statistical_review_required_headings()[[7L]]), fixed = TRUE)))
# 5) approve 拒绝未 approved/published 的 review。
stopifnot(inherits(try(approve_and_generate_analysis(study_dir, project_dir, "Synthetic Reviewer"), silent = TRUE), "try-error"))
# 6) 恢复：valid → approved；planned → approved；linked → approved。
restored <- compile_and_finalize(plan); stopifnot(restored$approved, restored$analysis_count == 1L)
planned_plan <- plan; planned_plan$execution_context[c("data_availability", "data_classification", "intended_use")] <- list("none", "none", "code_generation"); planned_plan$analyses[[1]]$dataset <- list(binding_mode = "planned", file = "scores.csv", format = "csv", relative_path = NULL, sha256 = NULL); planned_result <- compile_and_finalize(planned_plan); stopifnot(planned_result$approved, planned_result$analysis_count == 1L)
linked_restored <- compile_and_finalize(plan); stopifnot(linked_restored$approved)
# 7) approve 只消费 approved/published：生成 contract+programs，不改 review 状态。
chain <- approve_and_generate_analysis(study_dir, project_dir, "Synthetic Reviewer"); stopifnot(identical(chain$review$metadata$review_status, "approved"), identical(as.character(chain$review$metadata$finalization_status), "published"), file.exists(analysis_contract_path(study_dir)), file.exists(file.path(study_dir, "analysis", "r", "MMRM-01.R")), file.exists(file.path(study_dir, "analysis", "r", "run_all_mmrm.R")), file.exists(file.path(study_dir, "analysis", "sas", "MMRM-01.sas")), !file.exists(file.path(study_dir, "analysis", "sas", "MMRM-01_template.sas")))
# 8) blocked 渲染：丢弃陈旧 PLAN-*，保留非 PLAN 行，追加当轮机器问题（无累积）。
stale_existing <- data.frame(issue_id = c("PLAN-SCHEMA-STALE", "REVIEW/T14-01/fixed_effects"), scope = c("ALL", "T14-01"), question_or_risk = c("old machine blocker", "genuine open item"), resolution = c("n/a", "pending"), status = c("unresolved", "unresolved"), stringsAsFactors = FALSE, check.names = FALSE)
fresh_generated <- review_finalize_issue_frame("PLAN-MODEL-INVALID", "ALL", "covariance", "observed", "requirement", "fix")
blocked_section <- review_finalize_render_blocked_section(stale_existing, fresh_generated)
stopifnot(!any(grepl("PLAN-SCHEMA-STALE", blocked_section, fixed = TRUE)), any(grepl("REVIEW/T14-01/fixed_effects", blocked_section, fixed = TRUE)), any(grepl("PLAN-MODEL-INVALID", blocked_section, fixed = TRUE)))
unlink(study_dir, recursive = TRUE, force = TRUE); stopifnot(!dir.exists(study_dir)); cat("Analysis plan finalization and approval hash focused check passed.\n")
