options(encoding = "UTF-8")
args <- commandArgs(trailingOnly = TRUE)
get_arg <- function(name, required = TRUE, default = NULL) { prefix <- paste0("--", name, "="); values <- args[startsWith(args, prefix)]; if (!length(values)) { if (required) stop("Missing --", name, "=<value>."); return(default) }; if (length(values) != 1L) stop("Argument may appear once: --", name); substring(values, nchar(prefix) + 1L) }
find_project_root <- function(path) { current <- normalizePath(path, winslash = "/", mustWork = TRUE); repeat { if (file.exists(file.path(current, ".codex", "study-mmrm-analysis", "R", "case_summary.R"))) return(current); parent <- dirname(current); if (identical(parent, current)) stop("Cannot locate project root."); current <- parent } }
study_dir <- normalizePath(get_arg("study-dir"), winslash = "/", mustWork = TRUE); project_dir <- find_project_root(study_dir); skill_r <- file.path(project_dir, ".codex", "study-mmrm-analysis", "R")
for (helper in c("study_paths.R", "io.R", "specification.R", "canonical_hash.R", "standard_contract.R", "standard_analysis_definition.R", "analysis_plan.R", "analysis_contract_generation.R", "analysis_approval.R", "standard_engine.R", "standard_artifacts.R", "case_summary.R")) source(file.path(skill_r, helper), encoding = "UTF-8")
script_file <- file.path(study_dir, "analysis", "r", "run_all_mmrm.R"); if (!file.exists(script_file)) stop("Generated collector not found: ", script_file)
paths <- study_paths(script_file); chain <- assert_approved_analysis(study_dir, project_dir); contract <- chain$contract
if (!file.exists(paths$output_manifest)) stop("tfl-output-manifest.csv not found; run the generated collector first.")
output_arg <- get_arg("output", required = FALSE, default = file.path("backup-trace", "study-case-summary.yaml")); output_path <- if (grepl("^[A-Za-z]:[/\\\\]|^[/\\\\]", output_arg)) normalizePath(output_arg, winslash = "/", mustWork = FALSE) else normalizePath(file.path(study_dir, output_arg), winslash = "/", mustWork = FALSE)
study_root <- paste0(normalizePath(study_dir, winslash = "/", mustWork = TRUE), "/"); if (!startsWith(tolower(output_path), tolower(study_root))) stop("Case summary must be written inside the current study.")
dir.create(dirname(output_path), recursive = TRUE, showWarnings = FALSE); write_standard_case_summary(paths, chain, output_path); cat("Validated study case summary written: ", output_path, "\n", sep = "")
